rand_string change 3 (and header file)
random.c is completed alongside the inclusion of a header file by the same name, required in order for the main file to run a separate C file. Executable made (via Git Bash) in order to run both C files without errors regarding 'undefined reference to rand_string'.